{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b79a5d15",
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d4f7a51f",
   "metadata": {},
   "outputs": [],
   "source": [
    "def uploadDataApi(filePath: str, endpoint: str) -> str:\n",
    "    \"\"\"\n",
    "    upload the data to the api\n",
    "    Args:\n",
    "        filePath (str): path to the file to upload\n",
    "        endpoint (str): endpoint to upload to\n",
    "\n",
    "    Returns:\n",
    "        str: url of the uploaded file\n",
    "    \"\"\"\n",
    "    files = {'file': open(filePath, 'rb')}\n",
    "    r = requests.post(endpoint, files=files)\n",
    "    return r"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cbc3c47d",
   "metadata": {},
   "source": [
    "### Protected Area widget"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "fd7956e7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# i am here trusting that the data output from protected_areas_widget_validator_test.ipynb \n",
    "# is already validated and exported to a csv file\n",
    "\n",
    "urlApiEndpoint = 'https://mangrove-atlas-api.herokuapp.com/api/v2/widgets/protected-areas/import'\n",
    "file = './../../../datasets/processed/Mangrove_protected_area.csv'\n",
    "response = uploadDataApi(file, urlApiEndpoint) # 200 - success\n",
    "response.json()\n",
    "# check = pd.read_csv(file)\n",
    "# print(check.info())\n",
    "# check[['location_id', 'total_area', 'protected_area', 'year']].to_csv(file, index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "5e3c697b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'status': 422,\n",
       " 'error': 'Unprocessable Entity',\n",
       " 'exception': '#<ActiveRecord::RecordInvalid: Validation failed: Location must exist>',\n",
       " 'traces': {'Application Trace': [{'exception_object_id': 209120,\n",
       "    'id': 14,\n",
       "    'trace': \"app/models/widget_protected_areas.rb:30:in `block in import'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 27,\n",
       "    'trace': \"app/models/widget_protected_areas.rb:22:in `import'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 28,\n",
       "    'trace': \"app/controllers/v2/widgets_controller.rb:8:in `protected_areas_import'\"}],\n",
       "  'Framework Trace': [{'exception_object_id': 209120,\n",
       "    'id': 0,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/validations.rb:80:in `raise_validation_error'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 1,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/validations.rb:53:in `save!'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 2,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/transactions.rb:302:in `block in save!'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 3,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 4,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 5,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 6,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 7,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 8,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 9,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 10,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 11,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/transactions.rb:350:in `with_transaction_returning_status'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 12,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/transactions.rb:302:in `save!'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 13,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/suppressor.rb:54:in `save!'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 15,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:1128:in `emit_row'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 16,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:873:in `block in parse_quotable_loose'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 17,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:52:in `block in each_line'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 18,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:49:in `each_line'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 19,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:49:in `each_line'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 20,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:825:in `parse_quotable_loose'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 21,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:336:in `parse'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 22,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:2345:in `each'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 23,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:2345:in `each'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 24,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:1206:in `block in foreach'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 25,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:1438:in `open'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 26,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:1205:in `foreach'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 29,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 30,\n",
       "    'trace': \"actionpack (7.0.0) lib/abstract_controller/base.rb:214:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 31,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/rendering.rb:53:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 32,\n",
       "    'trace': \"actionpack (7.0.0) lib/abstract_controller/callbacks.rb:234:in `block in process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 33,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/callbacks.rb:99:in `run_callbacks'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 34,\n",
       "    'trace': \"actionpack (7.0.0) lib/abstract_controller/callbacks.rb:233:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 35,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/rescue.rb:22:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 36,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 37,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/notifications.rb:206:in `block in instrument'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 38,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 39,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/notifications.rb:206:in `instrument'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 40,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/instrumentation.rb:66:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 41,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 42,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/railties/controller_runtime.rb:27:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 43,\n",
       "    'trace': \"actionpack (7.0.0) lib/abstract_controller/base.rb:151:in `process'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 44,\n",
       "    'trace': \"actionview (7.0.0) lib/action_view/rendering.rb:39:in `process'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 45,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal.rb:188:in `dispatch'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 46,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal.rb:251:in `dispatch'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 47,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 48,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 49,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/journey/router.rb:50:in `block in serve'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 50,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/journey/router.rb:32:in `each'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 51,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/journey/router.rb:32:in `serve'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 52,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/routing/route_set.rb:850:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 53,\n",
       "    'trace': \"rack (2.2.3) lib/rack/etag.rb:27:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 54,\n",
       "    'trace': \"rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 55,\n",
       "    'trace': \"rack (2.2.3) lib/rack/head.rb:12:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 56,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/migration.rb:603:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 57,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 58,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/callbacks.rb:99:in `run_callbacks'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 59,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 60,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 61,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 62,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 63,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 64,\n",
       "    'trace': \"railties (7.0.0) lib/rails/rack/logger.rb:36:in `call_app'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 65,\n",
       "    'trace': \"railties (7.0.0) lib/rails/rack/logger.rb:25:in `block in call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 66,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/tagged_logging.rb:99:in `block in tagged'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 67,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/tagged_logging.rb:37:in `tagged'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 68,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/tagged_logging.rb:99:in `tagged'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 69,\n",
       "    'trace': \"railties (7.0.0) lib/rails/rack/logger.rb:25:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 70,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 71,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/request_id.rb:26:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 72,\n",
       "    'trace': \"rack (2.2.3) lib/rack/runtime.rb:22:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 73,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 74,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/server_timing.rb:20:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 75,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 76,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/static.rb:23:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 77,\n",
       "    'trace': \"rack (2.2.3) lib/rack/sendfile.rb:110:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 78,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 79,\n",
       "    'trace': \"rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 80,\n",
       "    'trace': \"railties (7.0.0) lib/rails/engine.rb:530:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 81,\n",
       "    'trace': \"puma (5.5.2) lib/puma/configuration.rb:249:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 82,\n",
       "    'trace': \"puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 83,\n",
       "    'trace': \"puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 84,\n",
       "    'trace': \"puma (5.5.2) lib/puma/request.rb:76:in `handle_request'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 85,\n",
       "    'trace': \"puma (5.5.2) lib/puma/server.rb:447:in `process_client'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 86,\n",
       "    'trace': \"puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'\"}],\n",
       "  'Full Trace': [{'exception_object_id': 209120,\n",
       "    'id': 0,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/validations.rb:80:in `raise_validation_error'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 1,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/validations.rb:53:in `save!'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 2,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/transactions.rb:302:in `block in save!'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 3,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 4,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 5,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 6,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 7,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 8,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 9,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 10,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 11,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/transactions.rb:350:in `with_transaction_returning_status'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 12,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/transactions.rb:302:in `save!'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 13,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/suppressor.rb:54:in `save!'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 14,\n",
       "    'trace': \"app/models/widget_protected_areas.rb:30:in `block in import'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 15,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:1128:in `emit_row'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 16,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:873:in `block in parse_quotable_loose'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 17,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:52:in `block in each_line'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 18,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:49:in `each_line'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 19,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:49:in `each_line'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 20,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:825:in `parse_quotable_loose'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 21,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv/parser.rb:336:in `parse'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 22,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:2345:in `each'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 23,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:2345:in `each'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 24,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:1206:in `block in foreach'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 25,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:1438:in `open'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 26,\n",
       "    'trace': \"/usr/local/lib/ruby/3.0.0/csv.rb:1205:in `foreach'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 27,\n",
       "    'trace': \"app/models/widget_protected_areas.rb:22:in `import'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 28,\n",
       "    'trace': \"app/controllers/v2/widgets_controller.rb:8:in `protected_areas_import'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 29,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 30,\n",
       "    'trace': \"actionpack (7.0.0) lib/abstract_controller/base.rb:214:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 31,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/rendering.rb:53:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 32,\n",
       "    'trace': \"actionpack (7.0.0) lib/abstract_controller/callbacks.rb:234:in `block in process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 33,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/callbacks.rb:99:in `run_callbacks'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 34,\n",
       "    'trace': \"actionpack (7.0.0) lib/abstract_controller/callbacks.rb:233:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 35,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/rescue.rb:22:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 36,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 37,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/notifications.rb:206:in `block in instrument'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 38,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 39,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/notifications.rb:206:in `instrument'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 40,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/instrumentation.rb:66:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 41,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 42,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/railties/controller_runtime.rb:27:in `process_action'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 43,\n",
       "    'trace': \"actionpack (7.0.0) lib/abstract_controller/base.rb:151:in `process'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 44,\n",
       "    'trace': \"actionview (7.0.0) lib/action_view/rendering.rb:39:in `process'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 45,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal.rb:188:in `dispatch'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 46,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_controller/metal.rb:251:in `dispatch'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 47,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 48,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 49,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/journey/router.rb:50:in `block in serve'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 50,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/journey/router.rb:32:in `each'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 51,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/journey/router.rb:32:in `serve'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 52,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/routing/route_set.rb:850:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 53,\n",
       "    'trace': \"rack (2.2.3) lib/rack/etag.rb:27:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 54,\n",
       "    'trace': \"rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 55,\n",
       "    'trace': \"rack (2.2.3) lib/rack/head.rb:12:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 56,\n",
       "    'trace': \"activerecord (7.0.0) lib/active_record/migration.rb:603:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 57,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 58,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/callbacks.rb:99:in `run_callbacks'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 59,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 60,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 61,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 62,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 63,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 64,\n",
       "    'trace': \"railties (7.0.0) lib/rails/rack/logger.rb:36:in `call_app'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 65,\n",
       "    'trace': \"railties (7.0.0) lib/rails/rack/logger.rb:25:in `block in call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 66,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/tagged_logging.rb:99:in `block in tagged'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 67,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/tagged_logging.rb:37:in `tagged'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 68,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/tagged_logging.rb:99:in `tagged'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 69,\n",
       "    'trace': \"railties (7.0.0) lib/rails/rack/logger.rb:25:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 70,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 71,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/request_id.rb:26:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 72,\n",
       "    'trace': \"rack (2.2.3) lib/rack/runtime.rb:22:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 73,\n",
       "    'trace': \"activesupport (7.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 74,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/server_timing.rb:20:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 75,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 76,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/static.rb:23:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 77,\n",
       "    'trace': \"rack (2.2.3) lib/rack/sendfile.rb:110:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 78,\n",
       "    'trace': \"actionpack (7.0.0) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 79,\n",
       "    'trace': \"rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 80,\n",
       "    'trace': \"railties (7.0.0) lib/rails/engine.rb:530:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 81,\n",
       "    'trace': \"puma (5.5.2) lib/puma/configuration.rb:249:in `call'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 82,\n",
       "    'trace': \"puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 83,\n",
       "    'trace': \"puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 84,\n",
       "    'trace': \"puma (5.5.2) lib/puma/request.rb:76:in `handle_request'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 85,\n",
       "    'trace': \"puma (5.5.2) lib/puma/server.rb:447:in `process_client'\"},\n",
       "   {'exception_object_id': 209120,\n",
       "    'id': 86,\n",
       "    'trace': \"puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'\"}]}}"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "response = uploadDataApi(file, urlApiEndpoint) # 200 - success\n",
    "response.json()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb330f6d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
